pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["1__step.htm","Installation &#62; Datasource &#62; 1. Step: Preparation","1. Step: Preparation",""],
["2_step.htm","Installation &#62; Datasource &#62; 2. Step: Upload configs","2. Step: Upload configs",""],
["3_step_active_v3-server.htm","Installation &#62; Datasource &#62; 3. Step: Activate configs","3. Step: Activate configs",""],
["activate_properties.htm","Installation &#62; Datasource &#62; 3. Step: Activate configs &#62; Activate properties","Activate properties",""],
["activate_update-mechanism.htm","Installation &#62; Activate Update-mechanism","Activate Update-mechanism",""],
["activate_update-mechanism_2.htm","Operating Manual &#62; Update-mechanism","Activate Update-mechanism",""],
["adaption_of_elasticmapping.htm","Release Notes &#62; V2.8 &#62; Adaption of ElasticSearch-Mapping","Adaption of ElasticSearch-Mapping",""],
["adaption_of_elasticsearch-mapp.htm","Operating Manual &#62; Adaption of ElasticSearch-Mapping","Adaption of ElasticSearch-Mapping",""],
["address_already_in_use.htm","Operating Manual &#62; Address already in use","Address already in use",""],
["add_attribute.htm","Insight Configuration &#62; Insight Configuration Tools &#62; Insight Config Editor &#62; Add attribute","Add attribute",""],
["add_child.htm","Insight Configuration &#62; Insight Configuration Tools &#62; Insight Config Editor &#62; Add child","Add child",""],
["advanced_properties.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Advanced properties","Advanced properties",""],
["architecture_overview.htm","Architecture overview","Architecture overview",""],
["atomar_constraints.htm","Atomar Constraints","Atomar Constraints",""],
["attributecontrol.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; attributeControl","attributeControl",""],
["automatic_chunks.htm","Release Notes &#62; V2.8 &#62; Automatic chunks","Automatic chunks",""],
["backendinterna_deprecated.htm","Update &#62; V2.7 &#62; backendInterna deprecated","backendInterna deprecated",""],
["backendinterna_displaced2.htm","Release Notes &#62; V2.8 &#62; backendInterna displaced","backendInterna displaced",""],
["barcode.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Barcode","Barcode",""],
["barcodefilter.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; barcodeFilter","barcodeFilter",""],
["barcode_scanner_devices.htm","Operating Manual &#62; Barcode Scanner Devices","Barcode Scanner Devices",""],
["base_properties.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Base properties","Base properties",""],
["basicauth.htm","Installation &#62; Installation Insight Middleware &#62; Configuration &#62; BasicAuth","BasicAuth",""],
["basic_rules.htm","Insight Configuration &#62; Basic rules","Basic rules",""],
["bcm.htm","BCM","BCM",""],
["blocking_ip_or_user.htm","Release Notes &#62; V2.9 &#62; Blocking IP or User","Blocking IP or User",""],
["blocking_user_or_ip.htm","Operating Manual &#62; Blocking user or IP","Blocking user or IP",""],
["browser.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; browser","browser",""],
["browser_2_2.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; timeTrack","timeTrack",""],
["buckets.htm","Insight Configuration &#62; Layout &#62; Buckets","Buckets",""],
["changes_concerning_user_profil.htm","Update &#62; V15 &#62; Changes concerning user profile","Changes concerning user profile",""],
["changes_in_insight_properties.htm","Update &#62; V14 &#62; Changes in insight.properties","Changes in insight.properties",""],
["changing_default-port_of_elast.htm","Operating Manual &#62; Changing Default-Port of ElasticSearch","Changing Default-Port of ElasticSearch",""],
["changing_default-port_of_kiban.htm","Operating Manual &#62; Changing Default-Port of Kibana","Changing Default-Port of Kibana",""],
["chapter_2.htm","Installation","Installation",""],
["checks.htm","Update &#62; Standard-Update &#62; Checks","Checks",""],
["check_with_updatedb.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Check with updatedb","Check with updatedb",""],
["classification.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Classification","Classification",""],
["classifications.htm","Release Notes &#62; V2.4 &#62; Classifications","Classifications",""],
["clear.htm","Insight Configuration &#62; Layout &#62; clear","clear",""],
["client_configuration.htm","Insight Configuration &#62; Client Configuration","Client Configuration",""],
["client_url_parameters.htm","Insight Configuration &#62; Client URL Parameters","Client URL Parameters",""],
["common_actions.htm","Insight Configuration &#62; Menus and actions &#62; Common","Common",""],
["conditional_constraints.htm","Conditional Constraints","Conditional Constraints",""],
["configuration.htm","Insight Configuration","Insight Configuration",""],
["configure_action.htm","Installation &#62; Configure monitoring alerts &#62; Define Watcher &#62; Configure Action","Configure Action",""],
["configure_condition.htm","Installation &#62; Configure monitoring alerts &#62; Define Watcher &#62; Configure Condition","Configure Condition",""],
["configure_input.htm","Installation &#62; Configure monitoring alerts &#62; Define Watcher &#62; Configure Input","Configure Input",""],
["configure_monitoring_alers.htm","Installation &#62; Configure monitoring alerts","Configure monitoring alerts",""],
["confirm.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; confirm","confirm",""],
["constraint.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query &#62; constraint","constraint",""],
["constraint_example.htm","Constraint Example","Constraint Example",""],
["constraint_fields.htm","Constraint Fields","Constraint Fields",""],
["continious_login.htm","Operating Manual &#62; continous login","continous login",""],
["control.htm","Insight Configuration &#62; Layout &#62; control","control",""],
["cookienote.htm","Insight Configuration &#62; Client Configuration &#62; cookie","cookie",""],
["cookienote_releasenotes.htm","Release Notes &#62; V2.11 &#62; cookie","cookie",""],
["cookienote_releasenotes_2.htm","Release Notes &#62; V2.11 &#62; single action","single action",""],
["cookienote_releasenotes_2_2.htm","Release Notes &#62; V2.11 &#62; search this","searchThis action",""],
["cookienote_releasenotes_2_2_2.htm","Release Notes &#62; V2.11 &#62; list and table column widths","style for list and table columns",""],
["create.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; create","create",""],
["createform.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; createForm","createForm",""],
["createsilent.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; createSilent","createSilent",""],
["create_watcher.htm","Installation &#62; Configure monitoring alerts &#62; Define Watcher &#62; Create Watcher","Create Watcher",""],
["customizing_color_and_style.htm","Customizing color and style","Customizing color and style",""],
["dashboard.htm","Monitoring &#62; Logfiles &#62; Logstash-Dashboard","Logstash-Dashboard",""],
["dataimport_and_update_elastics.htm","Operating Manual &#62; Dataimport and Update Elasticsearch","Dataimport and Update Elasticsearch",""],
["datasource.htm","Installation &#62; Datasource","Datasource",""],
["datasource_in_jee-server.htm","Installation &#62; Datasource &#62; 1. Step: Preparation &#62; Datasource configuration","Datasource configuration",""],
["data_protection_notice.htm","Installation &#62; Push Notifications &#62; Data protection notice","Data protection notice",""],
["date.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Date","Date",""],
["db.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query &#62; db","db",""],
["debug_action.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; debug","debug",""],
["deeplink.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; barcodeDeepLink","barcodeDeeplink",""],
["deep_link_mobile.htm","Operating Manual &#62; Deep Link Mobile","Deep Link Mobile",""],
["defined_searches.htm","Insight Configuration &#62; Defined searches","Defined searches",""],
["define_properties_and_elements.htm","Insight Configuration &#62; Insight Configuration Tools &#62; Insight Config Editor &#62; Define properties and elements","Define properties and elements",""],
["deletelocal.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; deleteLocal","deleteLocal",""],
["deploy_datasource-backend.htm","Installation &#62; Datasource &#62; 1. Step: Preparation &#62; Deploy Datasource-Backend","Deploy Datasource-Backend",""],
["deploy_undeploy_war-files.htm","Operating Manual &#62; Deploy/Undeploy war-files","Deploy/Undeploy war-files",""],
["deploy_v3-server.htm","Installation &#62; Datasource &#62; 1. Step: Preparation &#62; Deploy v3-Server","Deploy v3-Server",""],
["derived_attributes.htm","Release Notes &#62; V2.8 &#62; Derived Attributes","Derived Attributes",""],
["derived_attributes2.htm","Insight Configuration &#62; Data Model &#62; Derived Attributes","Derived Attributes",""],
["derived_date_pattern_attribute.htm","Insight Configuration &#62; Data Model &#62; Derived Attributes &#62; Derived Date Pattern Attributes","Derived Date Pattern Attributes",""],
["derived_regex_attributes.htm","Insight Configuration &#62; Data Model &#62; Derived Attributes &#62; Derived Regex Attributes","Derived Regex Attributes",""],
["derived_replace_attributes.htm","Insight Configuration &#62; Data Model &#62; Derived Attributes &#62; Derived Replace Attributes","Derived Replace Attributes",""],
["detailslink.htm","Insight Configuration &#62; Layout &#62; detailsLink","detailsLink",""],
["details_action.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; details","details",""],
["dirtycheck.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; dirtyCheck","dirtyCheck",""],
["dnd.htm","Insight Configuration &#62; Drag and Drop (dnd)","Drag and Drop (dnd)",""],
["docker.htm","Installation &#62; Docker","Docker",""],
["docker_basic_setup.htm","Installation &#62; Docker &#62; Installation &#62; Basic Setup","Basic Setup",""],
["docker_installation.htm","Installation &#62; Docker &#62; Installation","Installation",""],
["docker_logging_monitoring.htm","Installation &#62; Docker &#62; Installation &#62; Log Aggregation","Log Aggregation",""],
["docker_log_access.htm","Installation &#62; Docker &#62; Installation &#62; Log Access","Log Access",""],
["docker_monitoring.htm","Installation &#62; Docker &#62; Installation &#62; Monitoring","Monitoring",""],
["docker_monitoring_2.htm","Installation &#62; Docker &#62; Installation &#62; Kibana","Kibana",""],
["document-handler-insight-release-notes.htm","Release Notes &#62; V2.11 &#62; Document-Handler-Insight","Document-Handler-Insight",""],
["document-handler-insight.htm","Installation &#62; Installation Insight Document &#62; Document-Handler-Insight","Document-Handler-Insight",""],
["documents.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Documents","Documents",""],
["documents_handler_maximo_addit.htm","Release Notes &#62; V2.11 &#62; Document-Handler-Maximo: Additional properties","Document-Handler-Maximo: Additional properties",""],
["document_type_file.htm","Release Notes &#62; V2.11 &#62; Document type File","Document type File",""],
["download.htm","Update &#62; V14 &#62; Warfiles for download mechanism","Warfiles for download mechanism",""],
["downloadrecord.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; downloadRecord","downloadRecord",""],
["download_cache.htm","Release Notes &#62; V2.8 &#62; Download cache","Download cache",""],
["download_meta_data.htm","Insight Configuration &#62; Insight Configuration Tools &#62; Insight Config Editor &#62; Download Meta Data","Download Meta Data",""],
["eam_subtype.htm","Update &#62; V16 &#62; Env variable SYSTEM_TYPE","Environment variable HYBRID_SYSTEM",""],
["elasticsearch.htm","Update &#62; V2.3 &#62; Middleware &#62; ElasticSearch","ElasticSearch",""],
["elasticsearch2.htm","Installation &#62; Installation Insight Middleware &#62; Start Services for Linux &#62; ElasticSearch","ElasticSearch",""],
["elastic_security_support.htm","Release Notes &#62; V2.8 &#62; Support of Elastic security","Support of Elastic security",""],
["electron-client.htm","User Manual &#62; Electron-Client","Electron-Client",""],
["encrypt_db-password.htm","Operating Manual &#62; Encrypt DB-Password","Encrypt DB-Password",""],
["environmentvariables.htm","Update &#62; V14 &#62; Environmentvariables","Environmentvariables",""],
["environment_variables.htm","Installation &#62; Installation Insight Middleware &#62; Environment Variables","Environment Variables",""],
["env__options.htm","Installation &#62; Docker &#62; Configuration","ENVIRONMENT options for Insight Images",""],
["excludeexpertsearch.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; excludeExpertSearch","excludeExpertSearch",""],
["excludeexpertsearch_2.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; excludeExpertSearch","excludeExpertSearch",""],
["expert-search_migration_changelog.htm","Update &#62; V2.8 &#62; Expert-Search Migration","Expert-Search Migration",""],
["explorer.htm","Insight Configuration &#62; Menus and actions &#62; Explorer","Explorer",""],
["extension_overview.htm","Extension overview","Extension overview",""],
["faq.htm","Installation &#62; Docker &#62; FAQ &#38; Example","FAQ &#38; Example",""],
["fieldvalidation.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Field validation &#62; existsValidator","existsValidator",""],
["filelink-release-notes.htm","Release Notes &#62; V2.11 &#62; FileLink","FileLink",""],
["filelink.htm","Insight Configuration &#62; FileLink","FileLink",""],
["filter.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; filter","filter",""],
["filtered_download.htm","Insight Configuration &#62; Offline – Data synchronization &#62; Filtered Download","Filtered Download",""],
["fingerprint.htm","Insight Configuration &#62; Fingerprint","Fingerprint",""],
["floating.htm","Insight Configuration &#62; Layout &#62; floating","floating",""],
["form.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; form","form",""],
["format.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Format","Format",""],
["formfield.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; formField","formField",""],
["gateway-dashboard_json.htm","Monitoring &#62; Gateway &#62; Gateway-Dashboard.json","Gateway-Dashboard.json",""],
["gateway.htm","Release Notes &#62; V2.8 &#62; Gateway","Gateway",""],
["gateway2.htm","Operating Manual &#62; Gateway","Gateway",""],
["gateway3.htm","Monitoring &#62; Gateway","Gateway",""],
["geo.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; geo","geo",""],
["gistx_full_alert.htm","Installation &#62; Configure monitoring alerts &#62; \"GISTX full\" alert","\"GISTX full\" alert",""],
["gotomenuaction.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; goto","goto",""],
["grouping.htm","Insight Configuration &#62; Layout &#62; Chunks and Grouping","Chunks and Grouping",""],
["grouping_2.htm","Insight Configuration &#62; Layout &#62; Sort by Attribute","Sort by Attribute",""],
["heapdump.htm","Operating Manual &#62; Heapdump","Heapdump",""],
["help_manual.htm","Insight Configuration &#62; Insight Configuration Tools &#62; Insight Config Editor &#62; Help Manual","Help Manual",""],
["https-config.htm","Installation &#62; Installation Apache HTTP Server &#62; HTTPS &#62; HTTPS Configuration","HTTPS Configuration",""],
["https-config_2.htm","Installation &#62; Installation Apache HTTP Server &#62; HTTPS &#62; HTTPS Verification &#38; FAQ","HTTPS Verification &#38; FAQ",""],
["https.htm","Installation &#62; Installation Apache HTTP Server &#62; HTTPS","HTTPS",""],
["images.htm","Installation &#62; Docker &#62; Images","Images",""],
["indexer2.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query &#62; indexer","indexer",""],
["indexerspecific_eam-propertie2.htm","Operating Manual &#62; Indexerspecific EAM-properties","Indexerspecific EAM-properties",""],
["indexerspecific_eam-properties.htm","Release Notes &#62; V2.10 &#62; Indexerspecific EAM-properties","Indexerspecific EAM-properties",""],
["indexer_management.htm","Release Notes &#62; V2.7 &#62; Indexer Management","Indexer Management",""],
["indexer_scheduling_.htm","Release Notes &#62; V2.8 &#62; Indexer scheduling ","Indexer scheduling ",""],
["inline.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; include attribute of a subsequent node","include attribute of a subsequent node",""],
["inlineonly.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; inlineOnly","inlineOnly",""],
["insert_create_nodes.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Advanced properties &#62; insert/create nodes","insert/create nodes",""],
["insight-auth_war.htm","Update &#62; V14 &#62; insight-auth.war","insight-auth.war",""],
["insight-document-handler-file.htm","Installation &#62; Installation Insight Document &#62; Document-Handler-File","Document-Handler-File",""],
["insight-document-handler-maxim.htm","Installation &#62; Installation Insight Document &#62; Document-Handler-Maximo","Document-Handler-Maximo",""],
["insight-logstash_as_a_service.htm","Monitoring &#62; Logfiles &#62; insight-logstash as a service","insight-logstash as a service",""],
["insight-profile_war.htm","Update &#62; V13 &#62; insight-profile.war","insight-profile.war",""],
["insight-status-alert.htm","Installation &#62; Configure monitoring alerts &#62; Insight-Status-alert","Insight-Status-alert",""],
["insight-status-alert_3.htm","Installation &#62; Configure monitoring alerts &#62; Define Watcher","Define Watcher",""],
["insight-status_as_a_windows-se.htm","Monitoring &#62; Processes &#62; insight-status as a windows service ","insight-status as a windows service ",""],
["insight-status_for_linux.htm","Monitoring &#62; Processes &#62; insight-status for Linux","insight-status for Linux",""],
["insight-status_sh.htm","Monitoring &#62; Processes &#62; insight-status Script","insight-status Script",""],
["insight-userprofile.htm","Update &#62; V2.7 &#62; insight-userprofile","insight-userprofile",""],
["insight-userprofile_json.htm","Insight Configuration &#62; insight-userprofile.json","insight-userprofile.json",""],
["insight-web_in_open-client.htm","using insight-web","using insight-web",""],
["insight_config_editor.htm","Insight Configuration &#62; Insight Configuration Tools &#62; Insight Config Editor","Insight Config Editor",""],
["insight_config_tool.htm","Insight Configuration &#62; Insight Configuration Tools","Insight Configuration Tools",""],
["insight_dashboard.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana","Dashboard Visualizations with Kibana",""],
["insight_documentv29.htm","Release Notes &#62; V2.9 &#62; Insight Document","Insight Document",""],
["insight_explorer_details_view_.htm","Release Notes &#62; V2.11 &#62; Insight Explorer,Attributes not writable in Details View","Insight Explorer,Attributes not writable in Details View",""],
["insight_migration.htm","Operating Manual &#62; Insight Migration","Insight Migration",""],
["insight_properties.htm","Update &#62; V2.11 &#62; insight.properties","insight.properties",""],
["insight_search.htm","Insight Configuration &#62; Public searches","Public searches",""],
["installation.htm","Installation &#62; Installation Apache HTTP Server &#62; Installation","Installation",""],
["installation_insight_db.htm","Installation &#62; Installation Insight DB","Installation Insight DB",""],
["installation_insight_db_2.htm","Installation &#62; Installation Insight Download","Installation Insight Download",""],
["installation_insight_db_2_2.htm","Installation &#62; Installation Insight Profile","Installation Insight Profile",""],
["installation_insight_db_2_2_2.htm","Installation &#62; Installation Insight Auth","Installation Insight Auth",""],
["installation_insight_document.htm","Installation &#62; Installation Insight Document","Installation Insight Document",""],
["installation_insight_gateway.htm","Installation &#62; Installation Insight Gateway","Installation Insight Gateway",""],
["installation_insight_log.htm","Installation &#62; Installation Insight Log","Installation Insight Log",""],
["installation_insight_migration.htm","Installation &#62; Installation Insight Migration","Installation Insight Migration",""],
["installation_insight_monitorin.htm","Installation &#62; Installation Insight Monitoring Administration","Installation Insight Monitoring Administration",""],
["installation_insight_profiledb.htm","Installation &#62; Installation Insight Server","Installation Insight Server",""],
["installation_insight_propertie.htm","Installation &#62; Installation Insight PropertiesWeb","Installation Insight PropertiesWeb",""],
["installation_insight_push_2.htm","Installation &#62; Push Notifications &#62; Installation Insight Push","Installation Insight Push",""],
["installation_insight_push_2_2.htm","Installation &#62; Push Notifications &#62; Enable Insight Push on Client","Enable Insight Push on Client",""],
["installation_sentinl.htm","Update &#62; V2.9 &#62; Sentinl for email alerts &#62; Installation Sentinl","Installation Sentinl",""],
["install_new_middleware.htm","Update &#62; V2.3 &#62; Middleware &#62; Install new Middleware","Install new Middleware",""],
["isready.htm","Insight Configuration &#62; Layout &#62; isReady","isReady",""],
["java_home.htm","Installation &#62; Installation Insight Middleware &#62; Start Services for Linux &#62; JAVA_HOME","JAVA_HOME",""],
["jetty.htm","Jetty","Jetty",""],
["jre.htm","Update &#62; V2.3 &#62; Middleware &#62; Delete middleware","Delete middleware",""],
["json_schema.htm","Insight Configuration &#62; Insight Configuration Tools &#62; json schema","json schema",""],
["kibana-monitor_json.htm","Monitoring &#62; Processes &#62; Monitoring-Dashboard.json","Monitoring-Dashboard.json",""],
["kibana.htm","Operating Manual &#62; Troubleshooting &#62; Kibana with firefox-browser doesn&#39;t work properly","Kibana with firefox-browser doesn&#39;t work properly",""],
["kibana2.htm","Installation &#62; Installation Insight Middleware &#62; Start Services for Linux &#62; Kibana","Kibana",""],
["kibana_dashboards.htm","Insight Configuration &#62; Kibana Dashboards","Kibana Dashboards",""],
["kibana_open_menu.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; kibanaOpen","kibanaOpen",""],
["labelhidden.htm","Insight Configuration &#62; Layout &#62; labelHidden","labelHidden",""],
["labelwidth.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; labelWidth","labelWidth",""],
["language.htm","Insight Configuration &#62; Client Configuration &#62; Language","Language",""],
["languages.htm","Insight Configuration &#62; Extend Languages","Extend Languages",""],
["layout.htm","Insight Configuration &#62; Layout","Layout",""],
["limitations_for_gistx-table.htm","Release Notes &#62; V2.10 &#62; Threshold for GISTX-Table","Threshold for GISTX-Table",""],
["list-table-style.htm","Insight Configuration &#62; Layout &#62; list/table style","list/table style",""],
["list.htm","Insight Configuration &#62; Layout &#62; list","list",""],
["listedit.htm","Insight Configuration &#62; Layout &#62; listEdit","listEdit",""],
["listeditmenuaction.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; listEdit","listEdit",""],
["list_and_execute_migrations.htm","Release Notes &#62; V2.8 &#62; List and execute migrations","List and execute migrations",""],
["logfiles.htm","Monitoring &#62; Logfiles","Logfiles",""],
["logging_for_insight-gateway.htm","Update &#62; V15 &#62; Logging for insight-gateway","Logging for insight-gateway",""],
["logging_sqls.htm","Operating Manual &#62; Logging SQLs","Logging SQLs",""],
["loginparams.htm","Insight Configuration &#62; Client Configuration &#62; loginParams","loginParams",""],
["logstash-config.htm","Update &#62; V2.9 &#62; Logstash-config","Logstash-config",""],
["logstash.htm","Installation &#62; Installation Insight Middleware &#62; Install Services for Windows &#62; Logstash","Logstash",""],
["logstash2.htm","Installation &#62; Installation Insight Middleware &#62; Start Services for Linux &#62; Logstash","Logstash",""],
["logstash_for_monitoring_logfil.htm","Release Notes &#62; V2.9 &#62; Logstash for monitoring Logfiles","Logstash for monitoring Logfiles",""],
["loop.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Children &#62; loop","loop",""],
["loop_sh.htm","Monitoring &#62; Processes &#62; loop Script","loop Script",""],
["ltpatoken.htm","Operating Manual &#62; Troubleshooting &#62; LtpaToken is invalid","LtpaToken is invalid",""],
["mail.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; mail","Mail",""],
["maps.htm","Insight Configuration &#62; Maps","Maps",""],
["map_menu.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; mapOpen","mapOpen / -Create / -Attach",""],
["mariadb.htm","Installation &#62; Installation Insight Middleware &#62; Install Services for Windows &#62; MariaDB","MariaDB",""],
["massdata.htm","Operating Manual &#62; massdata","massdata",""],
["maximo_logging.htm","Update &#62; V2.7 &#62; Maximo Logging","Maximo Logging",""],
["menus_and_action.htm","Insight Configuration &#62; Menus and actions","Menus and actions",""],
["menus_for_tabs.htm","Insight Configuration &#62; Favorites and Menu on Tabs","Favorites and Menu on Tabs",""],
["menu_request_maximo.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; request","request",""],
["middleware.htm","Release Notes &#62; V2.3 &#62; Middleware","Middleware",""],
["middleware2.htm","Update &#62; V2.3 &#62; Middleware","Middleware",""],
["middlware_for_linux_available.htm","Release Notes &#62; V2.9 &#62; Middlware for Linux available","Middlware for Linux available",""],
["migration_downloadentityindice.htm","Update &#62; V16 &#62; Migration DownloadEntityIndices","Migration DownloadEntityIndices",""],
["migration_of_downloadentity.htm","Update &#62; V15 &#62; Migration of DownloadEntity","Migration of DownloadEntity",""],
["migration_of_gateway-entries.htm","Update &#62; V2.9 &#62; Migration of Gateway-Entries","Migration of Gateway-Entries",""],
["mobile.htm","Insight Configuration &#62; Menus and actions &#62; Mobile","Mobile",""],
["mobile_app_update_android.htm","Update &#62; Standard-Update &#62; Update Insight Mobile &#62; Mobile App Update Android","Mobile App Update Android",""],
["mobile_client_update.htm","Update &#62; Standard-Update &#62; Update Insight Mobile &#62; Mobile Client Update","Mobile Client Update",""],
["mobile_client_update_rn.htm","Release Notes &#62; V2.8 &#62; Mobile Client Update","Mobile Client Update",""],
["monitoring.htm","Monitoring","Monitoring",""],
["monitoring_alerts_via_email_.htm","Release Notes &#62; V2.10 &#62; Monitoring Alerts via Email ","Monitoring Alerts via Email ",""],
["monitoring_of_gateway.htm","Release Notes &#62; V2.9 &#62; Monitoring of Gateway","Monitoring of Gateway",""],
["more_flexible_queryparams.htm","Release Notes &#62; V2.7 &#62; More flexible queryParams","More flexible queryParams",""],
["mustwrite.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; mustWrite","mustWrite",""],
["name_and_schedule.htm","Installation &#62; Configure monitoring alerts &#62; Define Watcher &#62; Enter Name and Schedule","Enter Name and Schedule",""],
["new_download.htm","Operating Manual &#62; New Download","New Download",""],
["new_insightdb_in_standalone_xm.htm","Update &#62; V2.7 &#62; new insightdb in standalone.xml","new insightdb in standalone.xml",""],
["new_tempdb.htm","Update &#62; V2.9 &#62; new datasource tempdb","new datasource tempdb",""],
["new_versions_of_insight-middle.htm","Update &#62; V15 &#62; New versions of insight-middleware","New versions of insight-middleware",""],
["next.htm","Insight Configuration &#62; Layout &#62; Input support &#62; next","next",""],
["next_release.htm","Release Notes &#62; V14.0","V14.0",""],
["next_release2.htm","Release Notes &#62; V15.0","V15.0",""],
["next_release3.htm","Release Notes &#62; V16.0","V16.0",""],
["next_release4.htm","Release Notes &#62; NEXT RELEASE","NEXT RELEASE",""],
["nfc.htm","Insight Configuration &#62; NFC","NFC",""],
["nfcread.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; nfcRead","nfcRead",""],
["no_icons.htm","Operating Manual &#62; Troubleshooting &#62; No icons","No icons",""],
["offline_menu.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; offline","offline",""],
["online_menu.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; online","online",""],
["open_open_parent.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; open, open parent","open, open parent",""],
["operating_manual.htm","Operating Manual","Operating Manual",""],
["options.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Value lists &#62; options","options",""],
["orderby.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query &#62; orderBy (deprecated)","orderBy (deprecated)",""],
["parentmapping.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query &#62; parentMapping","parentMapping",""],
["password_encryption.htm","Release Notes &#62; V2.8 &#62; Password encryption","Password encryption",""],
["password_encryption2.htm","Operating Manual &#62; Password encryption","Password encryption",""],
["performance_improvement.htm","Release Notes &#62; V2.10 &#62; Performance improvement","Performance improvement",""],
["performance_improvements.htm","Release Notes &#62; V2.8 &#62; Performance Improvements","Performance Improvements",""],
["performance_rebuildall.htm","Release Notes &#62; V2.9 &#62; Indexer Performance","Indexer Performance",""],
["phone.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Phone","Phone",""],
["planning.htm","Insight Configuration &#62; Planning","Planning",""],
["polling.htm","Polling from Insight","Polling from Insight",""],
["polling_from_insight_deprecate.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Replication of changed data &#62; GISTX table &#62; Polling from Insight","Polling from Insight",""],
["polling_gistx.htm","GISTX table","GISTX table",""],
["polling_gistx_2.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Replication of changed data &#62; GISTX table","GISTX table",""],
["preparation_for_linux.htm","Installation &#62; Installation Insight Middleware &#62; Preparation for Linux","Preparation for Linux",""],
["processes.htm","Monitoring &#62; Processes","Processes",""],
["properties.htm","Operating Manual &#62; Properties","Properties",""],
["properties_for_indexer.htm","Update &#62; V15 &#62; Properties for indexer","Properties for indexer",""],
["push.htm","Insight Configuration &#62; Push","Push",""],
["push_notifications.htm","Installation &#62; Push Notifications","Insight Push Notifications",""],
["qr.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; qr","qr",""],
["query.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query","query",""],
["queryparams-example-maximo.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; queryParams-Example-Maximo","queryParams-Example-Maximo",""],
["queryparams.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; queryParams","queryParams",""],
["reading_changed_data.htm","Replication of changed data","Replication of changed data",""],
["reading_changed_data_2.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Replication of changed data","Replication of changed data",""],
["readwrite.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Read/write","Read/write",""],
["redeploy_gateway.htm","Installation &#62; Datasource &#62; 3. Step: Activate configs &#62; redeploy gateway","redeploy gateway",""],
["redeploy_indexer.htm","Installation &#62; Datasource &#62; 3. Step: Activate configs &#62; redeploy indexer","redeploy indexer",""],
["ref456617601.htm","Insight Configuration &#62; Offline – Data synchronization","Offline – Data synchronization",""],
["ref456617933.htm","Insight Configuration &#62; Requirements","Requirements",""],
["ref456617933_1.htm","Requirements","Requirements",""],
["ref456617933_2.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Requirements","Requirements",""],
["ref456618281.htm","Insight Configuration &#62; Offline – Data synchronization &#62; Download strategy","Use case specific download strategy",""],
["ref456688161.htm","Insight Configuration &#62; Data Model","Data Model",""],
["ref456701241.htm","Insight Configuration &#62; Data Model &#62; Attributes","Attributes",""],
["ref457922217.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Assignment","Assignment",""],
["ref462392132.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Configuration &#62; Kibana &#62; Create a Visualization","Create a Visualization",""],
["ref462392134.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Configuration &#62; Kibana &#62; Create a Dashboard","Create a Dashboard",""],
["ref464057907.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Base properties","Base properties",""],
["refresh-action.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; refresh","refresh",""],
["relation3.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query &#62; relation","relation",""],
["reldb_url.htm","Update &#62; V2.13 &#62; insight.properties","insight.properties",""],
["release_notes.htm","Release Notes","Release Notes",""],
["remove.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; remove","remove",""],
["required.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Field validation &#62; required","required",""],
["requirements.htm","Monitoring &#62; Processes &#62; Requirements","Requirements",""],
["requirements2.htm","Monitoring &#62; Logfiles &#62; Requirements","Requirements",""],
["reverse_proxy.htm","Installation &#62; Docker &#62; Installation &#62; SSL-Proxy","SSL-Proxy",""],
["root3.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Root","Root",""],
["sap_jco_server.htm","Release Notes &#62; V13.3 &#62; V13.3.1 &#62; SAP JCo Server","SAP JCo Server",""],
["save_watcher.htm","Installation &#62; Configure monitoring alerts &#62; Define Watcher &#62; Save Watcher","Save Watcher",""],
["scheduled_deletion_of_old_not2.htm","Operating Manual &#62; Scheduled deletion of old notifications","Scheduled deletion of old notifications",""],
["scheduled_deletion_of_old_noti.htm","Release Notes &#62; V2.10 &#62; Scheduled deletion of old notifications","Scheduled deletion of old notifications",""],
["scheduler.htm","Operating Manual &#62; Scheduler","Scheduler",""],
["scriptfilter.htm","Insight Configuration &#62; Menus and actions &#62; Mobile &#62; scriptFilter","scriptFilter",""],
["search.htm","User Manual &#62; Search","Search",""],
["searchstring_contains_-.htm","User Manual &#62; Search &#62; Analysis of searchstring","Analysis of searchstring",""],
["searchthis.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; searchThis","searchThis",""],
["search_result_list.htm","Insight Configuration &#62; Layout &#62; View components &#62; Search Result List","Search Result List",""],
["sections.htm","Insight Configuration &#62; Layout &#62; Sections","Sections",""],
["selectfromtree.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Value lists &#62; selectFromTree","selectFromTree",""],
["select_action.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; select","select",""],
["self_service.htm","Operating Manual &#62; Self Service","Self Service",""],
["sending_to_insight.htm","Sending to Insight","Sending to Insight",""],
["sending_to_insight2.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Replication of changed data &#62; GISTX table &#62; Sending to Insight","Sending to Insight",""],
["sentinl_for_email_alerts.htm","Update &#62; V2.9 &#62; Sentinl for email alerts","Sentinl for email alerts",""],
["session-cookie.htm","Update &#62; V2.12 &#62; Session-Cookie","Session-Cookie",""],
["showclassifier.htm","Release Notes &#62; V2.11 &#62; Classification showClassifier","Classification showClassifier",""],
["sms.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Sms","Sms",""],
["sortby.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; sortBy","sortBy",""],
["sorting.htm","Release Notes &#62; V2.8 &#62; Sorting","Sorting",""],
["ssl_for_jee-container.htm","Operating Manual &#62; SSL for JEE-Container","SSL for JEE-Container",""],
["standard-middleware-update.htm","Update &#62; Standard-Middleware-Update","Standard-Middleware-Update",""],
["standard-update.htm","Update &#62; Standard-Update","Standard-Update",""],
["start_services_for_linux.htm","Installation &#62; Installation Insight Middleware &#62; Start Services for Linux","Start Services for Linux",""],
["staticcontent_menu.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; staticContent","staticContent",""],
["static_content.htm","Insight Configuration &#62; Client Configuration &#62; Static Content","Static Content",""],
["static_content_release_notes.htm","Release Notes &#62; V2.11 &#62; Static Content","Static Content",""],
["stopandnochildren.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; query &#62; indexer &#62; stopandnochildren","stopandnochildren",""],
["structure_of_expertsearch_chan.htm","Update &#62; V2.12 &#62; Structure of ExpertSearch changed","Structure of ExpertSearch changed",""],
["structure_of_nodeusersettings_.htm","Update &#62; V2.12 &#62; Structure of NodeUserSettings changed","Structure of NodeUserSettings changed",""],
["structure_of_notification_chan.htm","Update &#62; V2.12 &#62; Structure of Notification changed","Structure of Notification changed",""],
["strukture_changed_in_insightse.htm","Update &#62; V2.11 &#62; Structure of InsightSession changed","Structure of InsightSession changed",""],
["suffix.htm","Insight Configuration &#62; Layout &#62; suffix","suffix",""],
["systemparameters.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Systemproperties","Systemproperties",""],
["tab-action.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; tab","tab",""],
["table.htm","Insight Configuration &#62; Table","Table",""],
["table_open_menu.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; tableOpen","tableOpen",""],
["test_connectivity.htm","Installation &#62; Installation Insight PropertiesWeb &#62; Test connectivity","Test connectivity",""],
["test_gateway.htm","Installation &#62; Installation Insight Gateway &#62; Test Gateway","Test Gateway",""],
["test_migration_connectivity.htm","Installation &#62; Installation Insight Migration &#62; Test Migration connectivity","Test Migration connectivity",""],
["test_reldb.htm","Installation &#62; Installation Insight Reldb &#62; Test Reldb","Test Reldb",""],
["third-party_components_clients.htm","Third-Party Components Clients","Third-Party Components Clients",""],
["third-party_components_server.htm","Third-Party Components Server","Third-Party Components Server",""],
["timeouts.htm","Operating Manual &#62; Gateway &#62; Timeouts","Timeouts",""],
["timeouts_fuer_gateway.htm","Release Notes &#62; V2.10 &#62; Timeouts für Gateway","Timeouts für Gateway",""],
["timetrack.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; timeTrack","timeTrack",""],
["toc462989355.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Configuration","Configuration",""],
["toc462989356_2.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Configuration &#62; Insight Tree","Insight Tree",""],
["toc462989357.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Configuration &#62; Kibana","Kibana",""],
["toc462989358.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Configuration &#62; Kibana &#62; Define an index","Define an index",""],
["toc462989359.htm","Insight Configuration &#62; Dashboard Visualizations with Kibana &#62; Configuration &#62; Kibana &#62; Define a Search","Define a Search",""],
["toc464042955.htm","Installation &#62; Configuration IBM HTTP Server for Maximo &#62; Restart IBM HTTP-Server","Restart IBM HTTP-Server",""],
["toc464133678.htm","Insight Configuration &#62; Insight Config Editor","Insight Config Editor",""],
["toc464133678_2.htm","Insight Configuration &#62; Insight Configurations","Insight Configurations",""],
["toc464133679.htm","Insight Configuration &#62; Permissions","Permissions",""],
["toc464133681.htm","Insight Configuration &#62; Layout &#62; Main Menu","Main Menu",""],
["toc464133682.htm","Insight Configuration &#62; Layout &#62; Perspectives","Perspectives",""],
["toc464133683.htm","Insight Configuration &#62; Layout &#62; View components","View components",""],
["toc464133684.htm","Insight Configuration &#62; Layout &#62; Icons","Icons",""],
["toc464133685.htm","Insight Configuration &#62; Layout &#62; View components &#62; Main menu, initial view","Main menu, initial view",""],
["toc464133686.htm","Insight Configuration &#62; Layout &#62; View components &#62; Detail view","Detail view",""],
["toc464133687.htm","Insight Configuration &#62; Layout &#62; Input support","Input support",""],
["toc464133688.htm","Insight Configuration &#62; Layout &#62; Input support &#62; Widgets","Widgets",""],
["toc464133689.htm","Insight Configuration &#62; Layout &#62; Input support &#62; Barcode/QR-Code","Barcode/QR-Code",""],
["toc464133690.htm","Insight Configuration &#62; Layout &#62; Style","Style",""],
["toc464133691.htm","Insight Configuration &#62; Layout &#62; Color and font","Color and font",""],
["toc464133693.htm","Insight Configuration &#62; Data Model &#62; Nodes","Nodes",""],
["toc464133695.htm","Insight Configuration &#62; Data Model &#62; Nodes &#62; Children","Children",""],
["toc464133698.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Types","Types",""],
["toc464133699.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Value lists","Value lists",""],
["toc464133701.htm","Insight Configuration &#62; Push data","Push data",""],
["toc464133702.htm","Insight Configuration &#62; Push data &#62; Default push","Default push",""],
["toc464133703.htm","Insight Configuration &#62; Push data &#62; saveAction","saveAction",""],
["toc464133704.htm","Insight Configuration &#62; Push data &#62; OS-REST-API (Backend Maximo)","OS-REST-API (Backend Maximo)",""],
["toc464133707.htm","Insight Configuration &#62; Menus and actions &#62; Explorer &#62; insert","insert",""],
["toc464133711.htm","Insight Configuration &#62; Menus and actions &#62; Common &#62; save","save",""],
["toc464133715.htm","Insight Configuration &#62; Offline – Data synchronization &#62; Global settings","Global settings",""],
["toc464133720.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Field validation","Field validation",""],
["toc464133722.htm","Insight Configuration &#62; Default tree configurations","Default tree configurations",""],
["toc464222962.htm","Installation &#62; Requirements","Requirements",""],
["toc464222963.htm","Installation &#62; Requirements &#62; Environment","Environment",""],
["toc464222964.htm","Installation &#62; Requirements &#62; Browsers","Browsers",""],
["toc464222965.htm","Installation &#62; Requirements &#62; Files","Files",""],
["toc464222966.htm","Installation &#62; Requirements &#62; User for insight-middleware components","User for insight-middleware components",""],
["toc464222968.htm","Installation &#62; Installation Insight Connector for Maximo","Installation Insight Connector for Maximo",""],
["toc464222969.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Backup","Backup",""],
["toc464222970.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Extract files","Extract files",""],
["toc464222970_2.htm","Installation &#62; Installation Insight Connector for Maximo &#62; REST Session Timeout","Maximo REST-API Session Timeout",""],
["toc464222971.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Update Maximo system properties and database objects","Update Maximo system properties and database objects",""],
["toc464222972.htm","Installation &#62; Installation Insight Connector for Maximo &#62; Build &#38; Deploy","Build &#38; Deploy",""],
["toc464222973.htm","Installation &#62; Installation Apache HTTP Server","Installation Apache HTTP Server",""],
["toc464222974.htm","Installation &#62; Installation Apache HTTP Server &#62; Include Insight configuration","Include Insight configuration",""],
["toc464222974_2.htm","Installation &#62; Configuration IBM HTTP Server for Maximo &#62; Include Insight configuration","Include Insight configuration",""],
["toc464222975.htm","Installation &#62; Installation Apache HTTP Server &#62; Install as service","Install as service",""],
["toc464222976.htm","Installation &#62; Configuration IBM HTTP Server for Maximo","Configuration IBM HTTP Server for Maximo",""],
["toc464222981.htm","Installation &#62; Installation Insight Web","Installation Insight Web",""],
["toc464222982.htm","Installation &#62; Installation Insight Web &#62; Configuration","Configuration",""],
["toc464222983.htm","Installation &#62; Installation Insight Mobile","Installation Insight Mobile",""],
["toc464222984.htm","Installation &#62; Installation Insight Mobile &#62; Configuration","Configuration",""],
["toc464222985.htm","Installation &#62; Installation Insight Middleware","Installation Insight Middleware",""],
["toc464222986.htm","Installation &#62; Installation Insight Middleware &#62; Preparation for Windows","Preparation for Windows",""],
["toc464222987.htm","Installation &#62; Installation Insight Middleware &#62; Configuration","Configuration",""],
["toc464222988.htm","Installation &#62; Installation Insight Middleware &#62; Configuration &#62; Insight Properties","Insight Properties",""],
["toc464222990.htm","Installation &#62; Installation Insight Middleware &#62; Install Services for Windows","Install Services for Windows",""],
["toc464222991.htm","Installation &#62; Installation Insight Middleware &#62; Install Services for Windows &#62; Wildfly","Wildfly",""],
["toc464222993.htm","Installation &#62; Installation Insight Middleware &#62; Install Services for Windows &#62; ElasticSearch","ElasticSearch",""],
["toc464222995.htm","Installation &#62; Installation Insight Middleware &#62; Install Services for Windows &#62; Kibana","Kibana",""],
["toc464222996.htm","Installation &#62; Installation Insight Reldb","Installation Insight Reldb",""],
["toc464222997.htm","Installation &#62; Installation Insight EsProxy","Installation Insight EsProxy",""],
["toc464222998.htm","Installation &#62; Installation Insight Indexer","Installation Insight Indexer",""],
["toc464222999.htm","Installation &#62; Installation Insight Indexer &#62; Test Insight Indexer connectivity","Test Insight Indexer connectivity",""],
["toc464223000.htm","Installation &#62; Default tree configurations for Maximo","Default tree configurations for Maximo",""],
["toc464223002.htm","Installation &#62; Indexing trees","Indexing trees",""],
["toc464223112.htm","ExportSet and Extensions","ExportSet and Extensions",""],
["toc464223113.htm","Implementation of Interfaces","Implementation of Interfaces",""],
["toc464223114.htm","Configuration","Configuration",""],
["toc464223115.htm","openJET-Appserver","openJET-Appserver",""],
["toc464223116.htm","elasticBaseUrl","elasticBaseUrl",""],
["toc464223117.htm","insightBaseUrl","insightBaseUrl",""],
["toc464223118.htm","openJET-Client","openJET-Client",""],
["toc464223119.htm","searchAdmin-role","searchAdmin-role",""],
["toc464223120.htm","TreeConfigurations","TreeConfigurations",""],
["toc464555772.htm","Insight Configuration &#62; Public searches &#62; Create search","Create search",""],
["toc464555773.htm","Insight Configuration &#62; Public searches &#62; Store search","Store search",""],
["tomee.htm","Installation &#62; Installation Insight Middleware &#62; Start Services for Linux &#62; TomEE","TomEE",""],
["tomee2.htm","Operating Manual &#62; Encrypt DB-Password &#62; TomEE","TomEE",""],
["treeconfigurations.htm","Update &#62; V2.3 &#62; TreeConfigurations","TreeConfigurations",""],
["troubleshooting.htm","Operating Manual &#62; Troubleshooting","Troubleshooting",""],
["ui-featuresv28.htm","Release Notes &#62; V2.8 &#62; UI-Features","UI-Features",""],
["ui-featuresv29.htm","Release Notes &#62; V2.9 &#62; UI-FeaturesV29","UI-FeaturesV29",""],
["ui-features_v2_10.htm","Release Notes &#62; V2.10 &#62; UI-Features V2.10","UI-Features V2.10",""],
["update.htm","Update","Update",""],
["update_insight_connector_for_m.htm","Update &#62; Standard-Update &#62; Update Insight Connector for Maximo","Update Insight Connector for Maximo",""],
["update_insight_mobile.htm","Update &#62; Standard-Update &#62; Update Insight Mobile","Update Insight Mobile",""],
["update_insight_properties.htm","Update &#62; V2.8 &#62; Update gateway-properties in insight.properties","Update insight.properties",""],
["update_insight_web.htm","Update &#62; Standard-Update &#62; Update Insight Web","Update Insight Web",""],
["update_wildfly-components.htm","Update &#62; Standard-Update &#62; Update war-files on JEE-Server","Update war-files on JEE-Server",""],
["update_wildfly-components_2.htm","Update &#62; Standard-Update &#62; Update languagefiles on JEE-Server","Update languagefiles on JEE-Server",""],
["upgrade-process.htm","Update &#62; V2.8 &#62; Upgrade middleware","Upgrade middleware",""],
["upgrade_middleware.htm","Release Notes &#62; V2.8 &#62; new middleware","new middleware",""],
["url_for_gateway-statistics_cha.htm","Update &#62; V2.9 &#62; Url for gateway-statistics changed","Url for gateway-statistics changed",""],
["useful_migration_urls.htm","Installation &#62; Installation Insight Migration &#62; Useful migration urls","Useful migration urls",""],
["user_manual.htm","User Manual","User Manual",""],
["use_of_mssql_instead_of_h2.htm","Operating Manual &#62; Use of other database instead of H2","Use of other database instead of H2",""],
["use_of_mysql.htm","Operating Manual &#62; Use of other database instead of H2 &#62; Use of MySQL","Use of MySQL",""],
["using_jpgs_with_appropriate_qu.htm","Operating Manual &#62; Using images with appropriate quality","Using images with appropriate quality",""],
["using_smaler_jpgs.htm","Release Notes &#62; V13.3 &#62; V13.3.1 &#62; Using JPGs with appropriate quality","Using JPGs with appropriate quality",""],
["v13_3.htm","Release Notes &#62; V13.3","V13.3",""],
["v13_3_1.htm","Release Notes &#62; V13.3 &#62; V13.3.1","V13.3.1",""],
["v13_4.htm","Release Notes &#62; V13.4","V13.4",""],
["v14.htm","Update &#62; V14","V14",""],
["v15.htm","Update &#62; V15","V15",""],
["v16.htm","Update &#62; V16","V16",""],
["v17.htm","Update &#62; V17","V17",""],
["v17_0.htm","Release Notes &#62; V17.0","V17.0",""],
["v211.htm","Release Notes &#62; V2.11","V2.11",""],
["v212.htm","Release Notes &#62; V2.12","V2.12",""],
["v213.htm","Release Notes &#62; V2.13","V2.13",""],
["v2_10.htm","Release Notes &#62; V2.10","V2.10",""],
["v2_102.htm","Update &#62; V2.10","V2.10",""],
["v2_11.htm","Update &#62; V2.11","V2.11",""],
["v2_12.htm","Update &#62; V2.12","V2.12",""],
["v2_13.htm","Update &#62; V2.13","V2.13",""],
["v2_13_2.htm","Update &#62; V13","V2.13",""],
["v2_3.htm","Release Notes &#62; V2.3","V2.3",""],
["v2_32.htm","Update &#62; V2.3","V2.3",""],
["v2_4.htm","Release Notes &#62; V2.4","V2.4",""],
["v2_5.htm","Release Notes &#62; V2.5","V2.5",""],
["v2_52.htm","Update &#62; V2.5","V2.5",""],
["v2_7.htm","Release Notes &#62; V2.7","V2.7",""],
["v2_72.htm","Update &#62; V2.7","V2.7",""],
["v2_8.htm","Release Notes &#62; V2.8","V2.8",""],
["v2_82.htm","Update &#62; V2.8","V2.8",""],
["v2_8_warning.htm","Release Notes &#62; V2.8 &#62; WARNING","WARNING",""],
["v2_9.htm","Release Notes &#62; V2.9","V2.9",""],
["v2_92.htm","Update &#62; V2.9","V2.9",""],
["validation.htm","Insight Configuration &#62; Data Model &#62; Attributes &#62; Field validation &#62; validation","validation",""],
["vscode_editor.htm","Insight Configuration &#62; Insight Configuration Tools &#62; vscode editor","vscode editor",""],
["war-files.htm","war-files","war-files",""],
["wildfly.htm","Update &#62; V2.3 &#62; Middleware &#62; Wildfly","Wildfly",""],
["wildfly2.htm","Operating Manual &#62; Encrypt DB-Password &#62; Wildfly","Wildfly",""],
["wildfly_activemq_jms_broker.htm","Operating Manual &#62; Wildfly ActiveMQ queue administration","Wildfly ActiveMQ queue administration",""],
["wildfly_properties.htm","Update &#62; V2.7 &#62; Wildfly Properties","Wildfly Properties",""],
["wildfly_service.htm","Operating Manual &#62; Wildfly Service","Wildfly Service",""],
["working_with_variables.htm","Insight Configuration &#62; Working with variables/values","Working with variables/values",""]];
