---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-proxy
  labels:
    app: mas-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-proxy
  template:
    metadata:
      labels:
        app: mas-proxy
    spec:
      imagePullSecrets:
        - name: rodias-cr
      containers:
        - name: mas-proxy
          image: rodias.azurecr.io/mas-proxy:latest
          imagePullPolicy: Always
          env:
            - name: MAS_DOMAIN
              value: "mas.app.company.domain.tld"
            - name: MAS_INSTANCE
              value: "masdev"
            - name: PROXY_DOMAIN
              value: "masinsight.dev.app.company.tld"
          ports:
            - name: mas-proxy-port
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mas-proxy-svc
spec:
  ports:
    - name: svc-port
      port: 8080
      targetPort: mas-proxy-port
  selector:
    app: mas-proxy

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mas-proxy-ingress
  annotations:
    cert-manager.io/issuer: "le-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "60s"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - api.masinsight.dev.app.company.tld
      - auth.masinsight.dev.app.company.tld
      - masdev.manage.masinsight.dev.app.company.tld
    secretName: mas-proxy-tls
  rules:
  - host: 'auth.masinsight.dev.app.company.tld'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mas-proxy-svc
            port:
              name: svc-port
  - host: 'masdev.manage.masinsight.dev.app.company.tld'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mas-proxy-svc
            port:
              name: svc-port
  - host: 'api.masinsight.dev.app.company.tld'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mas-proxy-svc
            port:
              name: svc-port
