title: Configuration
nav:
    - overview
    - requirements
    - configuration_setup
    - backend-configuration
    - client-configuration
    - client_url_parameters
    - insight_config_tools
    - insightConfigurations
    - basicRules
    - permissions
    - dataModel
    - layout
    - tabView
    - customize
    - maximoAutomationscript
    - pushData
    - menuAndAction
    - favAndMenuOnTabs
    - drag_and_drop
    - offline_dataSynch
    - workingWithVariables
    - defaultTreeConfig
    - publicSearches
    - definedSearches
    - gantt
    - table
    - matrix
    - kibanaDashboards
    - dashboardVisualizationsKibana
    - push
    - fingerprint
    - fileLink
    - nfc
    - ocr
    - json
    - charts
    - hierarchySelection
    - pert
    - welcomePage
    - wizard
    - language
    - viewar
    - multiselection
    - reports
    - ifc
    - columnConfiguration
    - comments
    - csv
    - filesAndPhotos
    - map
    - sorting
    - contributions
